meunginx:
  image: nginx
  links:
    - meumariadb
    - meuphp6fpm
  ports:
    - "80:80"
meumariadb:
  image: mariadb
  environment:
    - MYSQL_ROOT_PASSWORD=1234
meuphp6fpm:
  image: php:5.6-fpm
  links:
    - meumariadb
  ports:
    - "9000:9000"